TARGET_URLS = {
    1: "https://www.lazydogrestaurants.com/locations/naperville-il/menu",
    2: "https://www.haciendarealnaperville.com/menu",
    3: "https://vaisnaperville.com/menu",
    4: "https://www.mesonsabika.com/menu",
    5: "https://www.santocielonaperville.com/menu",
    6: "https://www.vasiliskitchen.com/menu",
    7: "https://www.ramsaykitchen.com/naperville-menu",
    8: "https://www.entouragenaperville.com/menu",
    9: "https://order.online/store/hugo%27s-frog-bar-&-fish-house-naperville-69736",
    10: "https://order.tacopros.com",
    11: "https://traversosrestaurant.com/menu",
    12: "https://www.anchoandagave.com/menus/",
    13: "https://barlouie.com/menu/",
    14: "https://www.whitechocolategrill.com/menu",
    15: "https://biaggis.com/locations/illinois-naperville/#menu-divider",
    16: "https://plainfield-2.freedombrotherspizza.com/food-menu",
    17: "https://toast.app/r/little-pops-ny-pizzeria-naperville/order",
    18: "https://menu.thecheesecakefactory.com/il/naperville-228",
    19: "https://www.mortons.com/location/mortons-the-steakhouse-naperville-il/#dinner-mtnp",
    20: "https://www.jojosshakebar.com/popmenu-order",
    21: "https://www.thechopdlife.com/menus/",
    22: "https://spartanalehouse.toast.site/order/spartan-ale-house-naperville",
}
  
